### ISSUE TITLE
Complexity results

### ISSUE THREAD

**Issue by filippodebortoli** [lorenzleutgeb/ab#8]
Is there anything that we might say, about complexity?

In other words, is that the case that the transition from higher-order to first-order predicates lowers the complexity of ASP solving? If so, is any complexity added by allowing Java objects in place of interpretation for predicates/terms?

**Comment by lorenzleutgeb** [comment]
Sadly, there's nothing to gain here as going back to FOL does not bring us an improvement. For an elaboration check the HEX-program paper: One of the last sections explains how to reduce higher order atoms (without externals) to ordinary ASP. The case with external atoms is a little more complicated, but only since external sources may behave strangely. There is subsequent work on this which I referred to at the end of our introduction of HEX-programs.

Java object stuff should not change the complexity. Sure there is some overhead but the theoretical complexity does not really change.

**Comment by lorenzleutgeb** [comment]
Obvously, if your external source computes something huge and that takes an hour, this is bad, but I think it is assumed away by saying that runtime of external sources is constant or so. Anyway we are opening the box of the pandora here ...

**Comment by filippodebortoli** [comment]
Taking a look at the paper now.
I assume that it is safe to say that the set of _constant names_ is finite.
Referring to Theorem 8/9, and assuming that our external atoms are all computable in ExpTime (maybe we can also be stricter), then we have NEXP^{NP}-completeness.

Wondering if we can briefly mention this, or pointing to reference for complexity results.
What's your opinion?

**Comment by lorenzleutgeb** [comment]
Since we have the same complexity as the original work, we could say that complexity results are still applicable.
